#include <iostream>
#include <fstream>
#include <string>
#include <direct.h> // For _mkdir

int main()
{
    // Create the content for index.html
    std::string webContent = R"(
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <h1>Hello, Embedded World!</h1>
    <p>This page is entirely generated by C++.</p>
    <button id="myButton">Click Me!</button>
    <script>
        document.getElementById("myButton").onclick = function () {
            alert("Button clicked!");
        }
    </script>
</body>
</html>
)";

    // Ensure the build directory exists
    if (_mkdir("build") == -1 && errno != EEXIST)
    {
        std::cerr << "Error: Could not create build directory!" << std::endl;
        return 1;
    }

    // Write the content to build/index.html
    std::ofstream webFile("build/index.html");
    if (!webFile)
    {
        std::cerr << "Error: Could not create build/index.html file!" << std::endl;
        return 1;
    }

    webFile << webContent;

    if (webFile.fail())
    {
        std::cerr << "Error: Failed to write to build/index.html file!" << std::endl;
        return 1;
    }

    std::cout << "build/index.html file generated successfully!" << std::endl;

    return 0;
}