const global = {
	id: {
		selectContext: document.getElementById("selectContext"),
		elementStateSelect: document.getElementById("elementStateSelect"),
		elementSelect: document.getElementById("elementSelect"),
		sectionsVariables: document.getElementById("sectionsVariables"),
		mainBody: document.getElementById("mainBody"),
		wizardRootDiv: document.getElementById("wizardRootDiv"),
		preview: document.getElementById("preview"),
		noPreview: document.getElementById("noPreview"),
		styleRow: document.getElementById("styleRow"),
		wizardDiv: document.getElementById("wizardDiv"),
		leftSidebar: document.getElementById("leftSidebar"),
		wizardTitle: document.getElementById("wizardTitle"),
		wizardHeadDiv: document.getElementById("wizardHeadDiv"),
		wizardHeadTitle: document.getElementById("wizardHeadTitle"),
		wizardHeadMetaDescription: document.getElementById(
			"wizardHeadMetaDescription",
		),
		wizardHeadMetaKeywords: document.getElementById("wizardHeadMetaKeywords"),
		wizardFontsDiv: document.getElementById("wizardFontsDiv"),
		wizard: document.getElementById("wizard"),
		onlyLogo: document.getElementById("onlyLogo"),
		handOnLogo: document.getElementById("handOnLogo"),
		leftSidebarSwitchSide: document.getElementById("leftSidebarSwitchSide"),
		responsiveSelect: document.getElementById("responsiveSelect"),
		propertySelect: document.getElementById("propertySelect"),
		attributeSelect: document.getElementById("attributeSelect"),
		attributeDiv: document.getElementById("attributeDiv"),
		attributeInput: document.getElementById("attributeInput"),
		stateSelectAll: document.getElementById("stateSelectAll"),
		menuSave: document.getElementById("menuSave"),
		menuReload: document.getElementById("menuReload"),
		removeProperty: document.getElementById("removeProperty"),
		parent: document.getElementById("parent"),
		elementSelectAllDiv: document.getElementById("elementSelectAllDiv"),
		elementDiv: document.getElementById("elementDiv"),
		propertyDiv: document.getElementById("propertyDiv"),
		openState: document.getElementById("openState"),
		elementStateDiv: document.getElementById("elementStateDiv"),
		elementHeaderDiv: document.getElementById("elementHeaderDiv"),
		style: document.getElementById("style"),
		removeElement: document.getElementById("removeElement"),
		propertySelectAll: document.getElementById("propertySelectAll"),
		propertySelectAllDiv: document.getElementById("propertySelectAllDiv"),
		stateOf: document.getElementById("stateOf"),
		closeState: document.getElementById("closeState"),
		openAddState: document.getElementById("openAddState"),
		closeAddState: document.getElementById("closeAddState"),
		openAddElement: document.getElementById("openAddElement"),
		closeAddElement: document.getElementById("closeAddElement"),
		addElement: document.getElementById("addElement"),
		openAddScreen: document.getElementById("openAddScreen"),
		closeAddScreen: document.getElementById("closeAddScreen"),
		openAddProperty: document.getElementById("openAddProperty"),
		closeAddProperty: document.getElementById("closeAddProperty"),
		addProperty: document.getElementById("addProperty"),
		updateProperty: document.getElementById("updateProperty"),
		propertyInput: document.getElementById("propertyInput"),
		creatorSave: document.getElementById("creatorSave"),
		headAttributeDiv: document.getElementById("headAttributeDiv"),
		headSelectAttribute: document.getElementById("headSelectAttribute"),
		headSelectOption: document.getElementById("headSelectOption"),
		headInput: document.getElementById("headInput"),
		rootInput: document.getElementById("rootInput"),
		rootSelectVariable: document.getElementById("rootSelectVariable"),
		selectStateOfContext: document.getElementById("selectStateOfContext"),
		contextSelectAllDiv: document.getElementById("contextSelectAllDiv"),
		stateOfContextSelectAllDiv: document.getElementById("stateOfContextSelectAllDiv"),
	},
	class: {
		smallButtons: "smallButtons",
		remove: "remove",
		labelDiv: "labelDiv",
		shaded: "shaded",
		smaller: "smaller",
		right: "right",
	},
	map: {
		headMap: new Map(),
		fontMap: new Map(),
		rootMap: new Map(),
		cssMap: new Map(),
		mediaQueriesMap: new Map(),
	},
};
