export default function getHtmlAttributes() {
	// Create a dummy element to access the full list of possible attributes

	// Access the attributes object, which contains all possible attributes

	// Iterate over all attributes and collect their names

	// Add common global attributes manually
	const allHtmlAttributes = [
		// Global attributes
		"accesskey",
		"autocapitalize",
		"autofocus",
		"class",
		"contenteditable",
		"contextmenu",
		"data-*", // Custom data attributes
		"dir",
		"draggable",
		"enterkeyhint",
		"exportparts",
		"hidden",
		"id",
		"inputmode",
		"is",
		"itemid",
		"itemprop",
		"itemref",
		"itemscope",
		"itemtype",
		"lang",
		"nonce",
		"part",
		"role",
		"slot",
		"spellcheck",
		"style",
		"tabindex",
		"title",
		"translate",

		// Event attributes (JavaScript)
		"onabort",
		"onautocomplete",
		"onautocompleteerror",
		"onblur",
		"oncancel",
		"oncanplay",
		"oncanplaythrough",
		"onchange",
		"onclick",
		"onclose",
		"oncontextmenu",
		"oncuechange",
		"ondblclick",
		"ondrag",
		"ondragend",
		"ondragenter",
		"ondragleave",
		"ondragover",
		"ondragstart",
		"ondrop",
		"ondurationchange",
		"onemptied",
		"onended",
		"onerror",
		"onfocus",
		"oninput",
		"oninvalid",
		"onkeydown",
		"onkeypress",
		"onkeyup",
		"onload",
		"onloadeddata",
		"onloadedmetadata",
		"onloadstart",
		"onmousedown",
		"onmouseenter",
		"onmouseleave",
		"onmousemove",
		"onmouseout",
		"onmouseover",
		"onmouseup",
		"onpause",
		"onplay",
		"onplaying",
		"onprogress",
		"onratechange",
		"onreset",
		"onresize",
		"onscroll",
		"onseeked",
		"onseeking",
		"onselect",
		"onshow",
		"onstalled",
		"onsubmit",
		"onsuspend",
		"ontimeupdate",
		"ontoggle",
		"onvolumechange",
		"onwaiting",
		"onwheel",

		// Form attributes
		"accept",
		"accept-charset",
		"action",
		"autocomplete",
		"autofocus",
		"enctype",
		"method",
		"name",
		"novalidate",
		"target",

		// Input-specific attributes
		"align",
		"alt",
		"autocomplete",
		"autofocus",
		"checked",
		"dirname",
		"disabled",
		"form",
		"formaction",
		"formenctype",
		"formmethod",
		"formnovalidate",
		"formtarget",
		"height",
		"list",
		"max",
		"maxlength",
		"min",
		"minlength",
		"multiple",
		"pattern",
		"placeholder",
		"readonly",
		"required",
		"size",
		"src",
		"step",
		"type",
		"value",
		"width",

		// Media attributes
		"autoplay",
		"controls",
		"loop",
		"muted",
		"preload",
		"src",

		// Audio/Video specific attributes
		"buffered",
		"crossorigin",
		"disableremoteplayback",
		"mediagroup",
		"playsinline",
		"poster",

		// Image attributes
		"alt",
		"crossorigin",
		"decoding",
		"height",
		"ismap",
		"loading",
		"referrerpolicy",
		"sizes",
		"src",
		"srcset",
		"usemap",
		"width",

		// Link attributes
		"charset",
		"href",
		"hreflang",
		"media",
		"referrerpolicy",
		"rel",
		"sizes",
		"target",
		"type",

		// Table attributes
		"border",
		"cellpadding",
		"cellspacing",
		"colspan",
		"headers",
		"rowspan",
		"scope",

		// Meta attributes
		"charset",
		"content",
		"http-equiv",
		"name",

		// Script attributes
		"async",
		"defer",
		"integrity",
		"nomodule",
		"referrerpolicy",
		"src",
		"type",

		// Style attributes
		"media",
		"scoped",
		"type",

		// Anchor attributes
		"download",
		"href",
		"hreflang",
		"ping",
		"referrerpolicy",
		"rel",
		"target",
		"type",

		// Miscellaneous attributes
		"cite",
		"datetime",
		"high",
		"low",
		"max",
		"min",
		"optimum",
		"span",
		"start",
		"value",
		"width",
	];

	// Combine the attributes from the dummy element and the global attributes
	return [...new Set([...allHtmlAttributes])];
}
